### ISSUE TITLE
Change the text color to black

### ISSUE THREAD

**Issue by Robophil** [PeterStaev/NativeScript-Drop-Down#48]
the code below doesn't seem to change the color of the text.
```css
.drop-down{
  text-align: center;
  color: black;
}
```
