### ISSUE TITLE
Cannot Style with Class

### ISSUE THREAD

**Issue by lukeramsden** [PeterStaev/NativeScript-Drop-Down#79]
>This is reproducible in the demo app.
# Expected Behavior
A dropdown with the `id` of `dd` and the `cssClass` of `input`, should be styled the same way by:
```css
#dd
{
    padding: 5;
    background-color: red;
    color: yellow;
}
```
and
```css
.input
{
    padding: 5;
    background-color: red;
    color: yellow;
}
```

# Actual Behavior
When styling `#dd`, it works fine, but when styling `.input` the styles aren't applied,
