### ISSUE TITLE
Arrow disappears after applying border style

### ISSUE THREAD

**Issue by YeshanJay** [PeterStaev/NativeScript-Drop-Down#91]
Hi,
The arrow on the widget disappears after applying border styles on it. See the images below.
Is there any way to keep both border and arrow?

CSS style:
```css
DropDown {
    margin: 10;
    padding: 2 2;
    font-size: 16;

    border-color: #000;
    border-width: 1;
    border-style: solid;
}
```

Without border:
![dd_noborder](https://cloud.githubusercontent.com/assets/28037630/25649335/1b45e6a8-2ff2-11e7-899d-96d229fe327e.png)

With border:
![dd_border](https://cloud.githubusercontent.com/assets/28037630/25649363/6e5ac2f0-2ff2-11e7-87e3-9ca99ab80d65.png)

**Comment by PeterStaev** [comment]
Hey @YeshanJay , this is a known limitation of the spinner android widget (not relative to {N}). 

As a workaround you can wrap the drop down in a StackLayout with `horizontalAlignment="stretch"` and apply the border on the layout.

**Comment by YeshanJay** [comment]
Hi @PeterStaev , 
Thanks a lot for the workaround. Makes me wonder why I couldn't think of that.. lol 😄

**Comment by DBhail** [comment]
How do you get rid of the underline within the dropdown (see image)? Tried the CSS to set bottom border to none but doesn't do anything. Would be nice to get rid of it:

![image](https://user-images.githubusercontent.com/32709854/31485463-d7111624-af2b-11e7-84a1-5cb346c63c34.png)

      <StackLayout class="input-field">
        <Label text="Type" class="label font-weight-bold m-b-5" textWrap="true"></Label>
        <StackLayout horizontalAlignment="stretch" class="input input-border">
          <DropDown [disabled]="!isEditMode()" #ddtype [items]="typeSelectionItems" [(ngModel)]="typeSelectionIndex" [hint]="hint"
            (selectedIndexChanged)="onTypeSelectionChange($event)" backroundColor="white" color="black" class="drop-down">
          </DropDown>
        </StackLayout>
      </StackLayout>

.drop-down{
    border: none;
    text-decoration: none; 
    border-bottom-width: 0;
    border-bottom-color: white;
    border-bottom: none;
}

**Comment by PeterStaev** [comment]
@DBhail the border is a default android style of the spinner. You can remove it AND the indicator on the right by using the hack to apply a border to the element:
```css
.drop-down {
    border-color: white;
    border-width: 1;
    border-style: solid;
}
```
